### PR TITLE
Scss refactor

### PR DESCRIPTION
**Pull request by EdCharbeneau**
Currently the FlightFinder app can be themed by changing a single variable. Also, I've switched to Bootstrap 4 Scss. The variables are now mapped to Bootstrap as well, so one change updates all UI components being used in FlightFInder including Bootstrap.

### CODE REVIEW

**Comment by Eilon** [comment]
@danroth27 if we take this, please do the needful by adding a third-party-notices.

**Comment by EdCharbeneau** [comment]
@Eilon @danroth27 I didn't take any new dependencies, I just switched from Bootstrap's .css to .scss codebase. Hopefully this helps.

**Comment by SteveSandersonMS** [comment]
@EdCharbeneau thanks for this! I'm really glad to be moving towards cleaner styling in this example.

What I'm not sure about however is adding all the jQuery and Bootstrap sources. I know it's common practice, but requiring 150+ files for this is hard to stomach. Do you think it would work to use the prebuilt Bootstrap and not involve jQuery at all?

**Comment by EdCharbeneau** [comment]
I agree, pulling in the whole of Boostrap and its dependencies isn't my favorite thing to do either. However, this is the "normal" way of doing things as this is what `npm install` would have done.

We could keep just the [/bootstrap/scss/](https://github.com/EdCharbeneau/samples/tree/scss-refactor/samples/aspnetcore/blazor/FlightFinder/FlightFinder.Client/scss/bootstrap/scss) folder and it's files. I can then refactor out the Bootstrap bits that we're not using in the demo. Keeping the Bootstrap .scss files is the best approach.

**Comment by camainc** [comment]
I'm not part of this team but I would like to add that I think keeping the /bootstrap/scss folder and files is the way to go. As someone using the demo to play around, I'd like the ability to easily modify the styling of the template, and having the scss files enables one to do that.

**Comment by EdCharbeneau** [comment]
@camainc Thanks for the input 👍 
@SteveSandersonMS I added a commit that only contains the /bootstrap/scss files. I've also customized the Bootstrap build so it only outputs the .css styles used in the app.

**Comment by SteveSandersonMS** [comment]
@EdCharbeneau Sorry we didn't get this merged. Basically I was concerned that it introduced new concerns that would distract from what the focus of the sample was meant to be and I never got round to finding a resolution to that. I still really appreciate you taking the time to make the contribution and hope we'll be able to include your contributions more effectively in the future!

**Comment by EdCharbeneau** [comment]
Thanks. I'll have to take a look again when I get a chance. I'm sure there's room for CSS improvement without utilizing Sass..

**Pull request closed without merging**
