### PR TITLE
Data access sample code with asp.net core and EF core.

### PR DESCRIPTION
**Pull request by Arnab-Developer**
I have added a sample application with asp.net core mvc and EF core. Also there is an unit test project.

### CODE REVIEW

**Comment by dnfgituser** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/aspnet/samples?pullRequest=58) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/aspnet/samples?pullRequest=58) before we can accept your contribution.<br/><br/>:x: Arnab-Developer [sign now](https://cla.dotnetfoundation.org/aspnet/samples?pullRequest=58)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/aspnet/samples?pullRequest=58) it.</sub>

**Review by Rickytoken — COMMENTED** [review]
By using inheritance bulid.java file

**Comment by Arnab-Developer** [comment]
@Rickytoken what do you mean by bulid.java file ?

**Comment by Rickytoken** [comment]
It is predefined function for core java where it can also overloading by developers code

**Comment by Arnab-Developer** [comment]
How it is relevant to this pull request?

**Comment by Arnab-Developer** [comment]
No activity for a long time. Closing this.

**Pull request closed without merging**
